// docgen generates Markdown documentation for prow-lite plugins and commands.
//
//go:generate go run ./cmd/docgen
package main

import (
	"os"
	"strings"
	"text/template"

	"github.com/patrickblackjr/prow-lite/cmd/labelsync"
	"github.com/patrickblackjr/prow-lite/internal/githubapi"
)

func main() {
	if err := os.MkdirAll("docs/plugins", 0o755); err != nil {
		panic(err)
	}

	render("docs/plugins/lgtm.md", lgtmTmpl, map[string]any{
		"Commands": githubapi.Commands,
		"PREvents": githubapi.PREvents,
		"Labels":   githubapi.EventPluginLabels,
	})

	render("docs/plugins/labelsync.md", labelsyncTmpl, labelsync.Plugin)
}

var funcs = template.FuncMap{
	"join": strings.Join,
	"inc":  func(i int) int { return i + 1 },
}

func render(path, tmpl string, data any) {
	f, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	if err := template.Must(template.New("").Funcs(funcs).Parse(tmpl)).Execute(f, data); err != nil {
		panic(err)
	}
	if err := f.Close(); err != nil {
		panic(err)
	}
}

const lgtmTmpl = `<!-- AUTO-GENERATED by cmd/docgen — do not edit by hand -->
# LGTM / Event Plugin

Handles PR approval and assignment via slash commands in PR comments.

## Triggers

GitHub ` + "`issue_comment`" + ` and ` + "`pull_request`" + ` webhook events.

## Slash Commands
{{range .Commands}}
### ` + "`{{join .Triggers \"` / `\"}}`" + `

{{.Description}}

` + "```" + `
{{.Usage}}
` + "```" + `
{{end}}
## Pull Request Lifecycle Events

| Action | Behavior |
|--------|----------|
{{- range .PREvents}}
| ` + "`{{.Action}}`" + ` | {{.Behavior}} |
{{- end}}

## Labels

| Label | Meaning |
|-------|---------|
{{- range .Labels}}
| ` + "`{{.Name}}`" + ` | {{.Meaning}} |
{{- end}}
`

const labelsyncTmpl = `<!-- AUTO-GENERATED by cmd/docgen — do not edit by hand -->
# {{.Name}} Plugin

{{.Description}}

{{.Trigger}}

## Configuration (` + "`.github/labels.yml`" + `)

| Field | Description | Default |
|-------|-------------|---------|
{{- range .Flags}}
| ` + "`{{.Name}}`" + ` | {{.Description}} | ` + "`{{.Default}}`" + ` |
{{- end}}

## Behavior

{{range $i, $step := .Behavior -}}
{{inc $i}}. {{$step}}
{{end}}`
