// docgen generates Markdown documentation for prow-lite plugins and commands.
//
//go:generate go run ./cmd/docgen
package main

import (
	"os"
	"strings"
	"text/template"

	"github.com/patrickblackjr/prow-lite/cmd/labelsync"
	"github.com/patrickblackjr/prow-lite/internal/githubapi"
)

func main() {
	if err := os.MkdirAll("docs/plugins", 0o755); err != nil {
		panic(err)
	}

	for _, plugin := range []githubapi.CommandPlugin{
		githubapi.LGTMPlugin,
		githubapi.AssignPlugin,
		githubapi.LabelPlugin,
	} {
		render("docs/plugins/"+plugin.Name+".md", commandPluginTmpl, plugin)
	}

	render("docs/plugins/labelsync.md", labelsyncTmpl, labelsync.Plugin)
}

var funcs = template.FuncMap{
	"join": strings.Join,
	"inc":  func(i int) int { return i + 1 },
}

func render(path, tmpl string, data any) {
	f, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	if err := template.Must(template.New("").Funcs(funcs).Parse(tmpl)).Execute(f, data); err != nil {
		panic(err)
	}
	if err := f.Close(); err != nil {
		panic(err)
	}
}

const commandPluginTmpl = `<!-- AUTO-GENERATED by cmd/docgen — do not edit by hand -->
# {{.Name}} plugin

{{.Description}}

## Triggers

{{.Trigger}}

## Slash commands
{{range .Commands}}
### ` + "`{{join .Triggers \"` / `\"}}`" + `

{{.Description}}

` + "```" + `
{{.Usage}}
` + "```" + `
{{end}}` +
	`{{if .PREvents}}
## Pull Request lifecycle events

| Action | Description |
|--------|-------------|
{{- range .PREvents}}
| ` + "`{{.Action}}`" + ` | {{.Description}} |
{{- end}}
{{end}}` +
	`{{if .Labels}}
## Labels

| Label | Meaning |
|-------|---------|
{{- range .Labels}}
| ` + "`{{.Name}}`" + ` | {{.Meaning}} |
{{- end}}
{{end}}` +
	`{{if .Notes}}
## Notes
{{range .Notes}}
- {{.}}
{{- end}}
{{end}}`

const labelsyncTmpl = `<!-- AUTO-GENERATED by cmd/docgen — do not edit by hand -->
# {{.Name}} plugin

{{.Description}}

{{.Trigger}}

## Configuration (` + "`.github/labels.yml`" + `)

| Field | Description | Default |
|-------|-------------|---------|
{{- range .Flags}}
| ` + "`{{.Name}}`" + ` | {{.Description}} | ` + "`{{.Default}}`" + ` |
{{- end}}

## Behavior

{{range $i, $step := .Behavior -}}
{{inc $i}}. {{$step}}
{{end}}`
