name: Run Prow Lite

on:
  issue_comment:
    types:
      - created

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.24.2"
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run Prow
        run: |
          go version
          go run .
