name: Prow Lite

on:
  issue_comment:
    types:
      - created

env:
  PROW_GITHUB_PRIVATE_KEY: ${{ secrets.PROW_GITHUB_PRIVATE_KEY }}

permissions:
  contents: write
  pull-requests: read

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.24.2"
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Convert GitHub event to single-line JSON
        run: |
          echo "EVENT=$(echo '${{ toJson(github.event) }}' | jq -c '.')" >> $GITHUB_ENV

      - name: Run Prow Lite
        run: |
          go version
          go run cmd/prow/main.go run --mode ci --plugin event --event "$EVENT"
