name: Prow Lite (Label Sync)

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/prow-labelsync.yml

env:
  PROW_GITHUB_PRIVATE_KEY: ${{ secrets.PROW_GITHUB_PRIVATE_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.24.2"
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Run Prow Lite (Label Sync)
        run: |
          go version
          go run . -module labelsync -run-mode ci
