name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.24"
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies and run tests
        run: |
          go mod tidy
          go test -cover -coverprofile=coverage.txt ./...

      - name: Upload coverage report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-report
          path: coverage.txt

  comment-coverage:
    if: github.event_name == 'pull_request'
    name: Comment coverage results on PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - uses: fgrosse/go-coverage-report@8c1d1a09864211d258937b1b1a5b849f7e4f2682 # v1.2.0
        with:
          coverage-artifact-name: coverage-report
          coverage-file-name: "coverage.txt"
